name: AdvancedPluginManager
main: ru.witwar.advancedpluginmanager.AdvancedPluginManager
version: prerelease1.0
author: witwar
commands:
  disable:
     description: Command for disable plugin.
     usage: /disable <pluginame>
  enable:
      description: Command for enable plugin.
      usage: /enable <pluginname>